Repository raster-foundry/blasterjs, pull requests merged in 2018-08, with the labels that each got.

#43 added directions, positions, shape, size enums
  packages/core/common/direction.js
  packages/core/common/position.js
  packages/core/common/shape.js
  packages/core/common/size.js
Labels: in progress

#44 Add prepare-release step to deployment documentation
  README.md
  docs/introduction.md
Labels: in progress

#45 added global resets, updated core exports
  docs/DocsThemeWrapper.js
  docs/introduction.md
  packages/core/defaultTheme.js
  packages/core/index.js
  packages/core/reset.css
  styleguide.config.js
Labels: cleanup :shower:, enhancement :sparkles:, in progress

#48 Add build step to copy core `reset.css`
  package.json
Labels: in progress

#49 Breadcrumbs
  packages/core/components/breadcrumbs/README.md
  packages/core/components/breadcrumbs/index.js
  packages/core/defaultTheme.js
  packages/core/index.js
Labels: enhancement :sparkles:, in review

#50 Add CLI and move to scripts directory
  .gitignore
  README.md
  bin/cli.js
  package.json
  packages/chart/index.common.js
  packages/chart/index.components.js
  packages/chart/index.js
  packages/core/index.common.js
  packages/core/index.components.js
  packages/core/index.js
  packages/core/package-lock.json
  packages/docs-app/index.common.js
  packages/docs-app/index.components.js
  packages/docs-app/index.js
  scripts/build
  scripts/clean
  scripts/release
  scripts/start
  templates/README.md
  templates/index.component.js
  templates/index.constant.js
  yarn.lock
Labels: in review

#58 fixes a breaking error in the start script
  scripts/start
Labels: in progress
